"""phase-24.3 (autoresearch-wiring) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_3.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.3` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.3", slug="autoresearch-wiring")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="anthropic_harness_design")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_documents_meta_evolution_cron_decoupling",
        pattern='meta_evolution.*cron|cron.*meta_evolution',
    )
    v.check_grep(
        claim_name="findings_documents_skill_optimizer_active_strategy_gap",
        pattern='SkillOptimizer|skill_optimizer',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
