"""phase-24.2 (pipeline-routing) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_2.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.2` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.2", slug="pipeline-routing")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="autonomous_loop_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_cites_autonomous_loop_branching_at_564_615",
        pattern='autonomous_loop\\.py.*56[0-9]|autonomous_loop\\.py.*61[0-9]',
    )
    v.check_grep(
        claim_name="findings_documents_why_full_28_skill_pipeline_is_unreached",
        pattern='28[- ]skill|full\\s+pipeline|lite_mode',
    )
    v.check_grep(
        claim_name="findings_traces_report_persistence_lite_vs_full_gap",
        pattern='_persist_lite_analysis|reports\\s+(?:gap|persistence)',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
