"""phase-24.14 (final-synthesis) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_14.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.14` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.14", slug="final-synthesis")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="phase_25")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="synthesis_lists_at_least_25_phase_25_candidates_ranked",
        pattern='phase-25\\.\\d',
    )
    v.check_grep(
        claim_name="synthesis_groups_candidates_by_priority_p0_p1_p2",
        pattern='P0|P1|P2|priority',
    )
    v.check_grep(
        claim_name="synthesis_each_candidate_has_audit_basis_back_reference",
        pattern='audit[- ]basis|audit_basis|back[- ]reference',
    )
    v.check_grep(
        claim_name="synthesis_emits_proposed_masterplan_step_entries_in_json",
        pattern='"id":\\s*"phase-25|"success_criteria"|masterplan.*entry',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
