"""phase-24.11 (frontend-data-wiring) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_11.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.11` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.11", slug="frontend-data-wiring")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="frontend_src_lib_api_ts")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_type_drift_between_pydantic_and_typescript",
        pattern='type\\s+drift|pydantic|typescript',
    )
    v.check_grep(
        claim_name="findings_audits_every_page_to_endpoint_mapping",
        pattern='page.*endpoint|endpoint.*page|14\\s+pages',
    )
    v.check_grep(
        claim_name="findings_audits_learnings_page_backend_hookup_gap",
        pattern='learnings\\s+page|/learnings|learnings.*backend',
    )
    v.check_grep(
        claim_name="findings_audits_auth_header_propagation",
        pattern='auth\\s+header|bearer\\s+token|authorization',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
