"""phase-24.4 (agent-rationale) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_4.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.4` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.4", slug="agent-rationale")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="multi_agent_orchestrator_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_documents_trader_riskjudge_byte_identical_text_with_file_line_anchor",
        pattern='byte[- ]identical|trader.*riskjudge|aliasing',
    )
    v.check_grep(
        claim_name="findings_explains_sparse_drawer_3_of_20_agents",
        pattern='3\\s+of\\s+\\d+|sparse\\s+drawer|drawer\\s+coverage',
    )
    v.check_grep(
        claim_name="findings_proposes_layer_1_28_skill_surfacing",
        pattern='layer[- ]1|28[- ]skill',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
