"""phase-24.8 (observability) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_8.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.8` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.8", slug="observability")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="observability_api_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_watchdog_wiring",
        pattern='watchdog',
    )
    v.check_grep(
        claim_name="findings_audits_killswitch_state_machine",
        pattern='kill[- ]switch|kill_switch',
    )
    v.check_grep(
        claim_name="findings_audits_sla_monitor_paths",
        pattern='SLA|sla_monitor',
    )
    v.check_grep(
        claim_name="findings_audits_cost_budget_enforcement",
        pattern='cost[- ]budget|cost_budget',
    )
    v.check_grep(
        claim_name="findings_audits_governance_limits_hot_reload",
        pattern='governance.*limits|limits.*hot[- ]reload',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
