"""phase-24.6 (backtest-engine) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_6.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.6` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.6", slug="backtest-engine")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="backtest_engine_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_walk_forward_correctness",
        pattern='walk[- ]forward',
    )
    v.check_grep(
        claim_name="findings_audits_seed_stability",
        pattern='seed[- ]stability|seed\\s+stab',
    )
    v.check_grep(
        claim_name="findings_audits_live_vs_backtest_reconciliation_drift",
        pattern='live[- ]vs[- ]backtest|reconciliation\\s+drift|backtest\\s+reconciliation',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
