"""phase-24.10 (mcp-security) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_10.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.10` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.10", slug="mcp-security")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="modelcontextprotocol_io")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_mcp_pinned_servers_alpaca_bigquery",
        pattern='alpaca.*bigquery|\\.mcp\\.json',
    )
    v.check_grep(
        claim_name="findings_audits_deny_rule_surface_completeness",
        pattern='deny\\s+rule|deny_rule',
    )
    v.check_grep(
        claim_name="findings_audits_nextauth_webauthn_flow",
        pattern='NextAuth|WebAuthn|passkey',
    )
    v.check_grep(
        claim_name="findings_audits_backend_env_secret_handling",
        pattern='backend/\\.env|secret\\s+handling|api\\s+key',
    )
    v.check_grep(
        claim_name="findings_proposes_new_mcps_signals_news_slack",
        pattern='signals\\s+MCP|news\\s+MCP|slack[- ]claude\\s+MCP|new\\s+MCP',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
