"""phase-24.1 (execution-trading) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_1.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.1` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.1", slug="execution-trading")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="paper_trader_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_cites_paper_trader_py_414_423_orphan_with_grep_evidence",
        pattern='paper_trader\\.py:?414|paper_trader\\.py.*414',
    )
    v.check_grep(
        claim_name="findings_tags_all_11_current_portfolio_positions_by_stop_presence",
        pattern='FIX.*MU.*KEYS|11\\s+(?:holdings|positions)',
    )
    v.check_grep(
        claim_name="findings_documents_ter_minus_12_30_no_sell_case",
        pattern='TER.*-1[12]\\.\\d+%|TER.*-12\\.30',
    )
    v.check_grep(
        claim_name="findings_audits_governance_limits_loader_watcher",
        pattern='backend/governance|limits[_ ]loader',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
