"""phase-24.9 (llm-conformance) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_9.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.9` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.9", slug="llm-conformance")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="anthropic_com_engineering")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_prompt_caching_depth_ephemeral_1h",
        pattern='prompt\\s+caching|cache_control',
    )
    v.check_grep(
        claim_name="findings_audits_extended_thinking_budgets",
        pattern='extended\\s+thinking|thinking\\s+budget',
    )
    v.check_grep(
        claim_name="findings_audits_tool_use_loop_max_turns",
        pattern='tool[- ]use|tool_use',
    )
    v.check_grep(
        claim_name="findings_audits_structured_output_schema_enforcement",
        pattern='structured\\s+output|response_schema',
    )
    v.check_grep(
        claim_name="findings_audits_google_search_grounding_usage",
        pattern='google\\s+search\\s+grounding|grounding',
    )
    v.check_grep(
        claim_name="findings_identifies_unused_anthropic_features_batch_files_citations",
        pattern='batch|files\\s+api|citations',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
