"""phase-24.5 (slack-notifications) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_5.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.5` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.5", slug="slack-notifications")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="slack_bot")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_documents_wrong_pnl_data_source_bug_with_file_line_anchor",
        pattern='\\$0\\.00|\\+0\\.0%|wrong\\s+(?:p&l|pnl)',
    )
    v.check_grep(
        claim_name="findings_documents_5x_sndk_recent_analyses_bug_with_query_anchor",
        pattern='SNDK|5x\\s+sndk|recent\\s+analyses\\s+bug',
    )
    v.check_grep(
        claim_name="findings_audits_morning_digest_2pm_schedule_bug",
        pattern='2:00\\s*PM|morning\\s+digest|schedule\\s+bug',
    )
    v.check_grep(
        claim_name="findings_enumerates_missing_notification_types_trade_killswitch_drawdown_error",
        pattern='trade\\s+confirmation|kill[- ]switch\\s+alert|drawdown\\s+alarm',
    )
    v.check_grep(
        claim_name="findings_audits_slash_commands_portfolio_analyze_report",
        pattern='/portfolio|/analyze|/report',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
