"""phase-24.12 (ui-ux-presentation) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_12.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.12` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.12", slug="ui-ux-presentation")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="claude_rules_frontend_md")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_design_system_conformance_phosphor_dark_scrollbar",
        pattern='phosphor|dark\\s+theme|scrollbar[- ]thin',
    )
    v.check_grep(
        claim_name="findings_audits_per_page_error_loading_empty_states",
        pattern='loading\\s+state|empty\\s+state|error\\s+state',
    )
    v.check_grep(
        claim_name="findings_audits_a11y_keyboard_aria_contrast",
        pattern='a11y|accessibility|aria|keyboard|contrast',
    )
    v.check_grep(
        claim_name="findings_audits_responsive_design_breakpoints",
        pattern='responsive|breakpoint|mobile|tablet',
    )
    v.check_grep(
        claim_name="findings_audits_cross_tab_kpi_reconciliation",
        pattern='cross[- ]tab|kpi\\s+reconciliation',
    )
    v.check_grep(
        claim_name="screenshots_dir_contains_at_least_14_images",
        pattern='screenshots/|playwright',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
