"""phase-24.7 (data-quality) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_7.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.7` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.7", slug="data-quality")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="bigquery_client_py")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="findings_audits_bq_table_freshness_across_datasets",
        pattern='freshness|pyfinagent_data|pyfinagent_hdw',
    )
    v.check_grep(
        claim_name="findings_audits_yfinance_fallback_pattern",
        pattern='yfinance|fallback',
    )
    v.check_grep(
        claim_name="findings_audits_signal_freshness",
        pattern='signal\\s+freshness|signal[- ]freshness',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
