"""phase-24.13 (redline-synthesis) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_13.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.13` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.13", slug="redline-synthesis")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="project_system_goal_md")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="synthesis_references_all_prior_buckets_24_1_through_24_9",
        pattern='24\\.1.*24\\.9|buckets\\s+24\\.[1-9]',
    )
    v.check_grep(
        claim_name="synthesis_quantifies_cost_vs_pnl_ratio",
        pattern='cost.*p&l|cost[- ]vs[- ]pnl|cost\\s+ratio',
    )
    v.check_grep(
        claim_name="synthesis_audits_strategy_switching_mechanism",
        pattern='strategy\\s+switching|strategy[- ]switch',
    )
    v.check_grep(
        claim_name="synthesis_audits_cost_budget_enforcement_path",
        pattern='cost\\s+budget\\s+enforcement|budget\\s+enforcement',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
