"""phase-24.0 (charter) verifier — audit-only.

Run: source .venv/bin/activate && python3 tests/verify_phase_24_0.py

Exits 0 on PASS, 1 on FAIL. All claims are immutable per `.claude/masterplan.json`
phase-24 step `24.0` verification.success_criteria. Generated by
/tmp/gen_phase_24_verifiers.py from the approved plan at
/Users/ford/.claude/plans/sunny-jingling-deer.md.

Shared assertion logic lives in `tests/_phase_24_helpers.py`. This file
only encodes bucket-specific anchor checks.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow the helper to import as a top-level module under tests/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _phase_24_helpers import Phase24Verifier  # noqa: E402


def main() -> int:
    v = Phase24Verifier(bucket_id="24.0", slug="charter")

    # --- common pack (10 claims) ---
    v.run_common_pack(canonical_url_key="anthropic_harness_design")

    # --- bucket-specific anchor checks ---
    v.check_grep(
        claim_name="charter_cites_project_system_goal_memory",
        pattern='project_system_goal',
    )
    v.check_grep(
        claim_name="charter_embeds_coverage_matrix_for_backend_frontend_infrastructure",
        pattern='coverage\\s+matrix',
    )
    v.check_grep(
        claim_name="charter_lists_15_buckets_24_0_through_24_14",
        pattern='24\\.14|fifteen\\s+buckets|15\\s+buckets',
    )
    v.check_grep(
        claim_name="charter_documents_research_gate_canonical_url_whitelist_per_bucket",
        pattern='canonical[- ]url',
    )
    v.check_grep(
        claim_name="charter_documents_findings_md_path_convention",
        pattern='findings\\.md|findings_md',
    )

    return v.finish()


if __name__ == "__main__":
    sys.exit(main())
