"""Regenerate a per-step evaluator_critique markdown record from the raw
Q/A return values persisted alongside it.

WHY THIS EXISTS
---------------
During phase-82.0 the critique record was maintained BY HAND and silently fell
behind: cycle 3's verdict was never transcribed, so the cycle-4 evaluator had to
take the prior verdict from the author's own summary of it. That destroys the
independence the transcription rule exists to protect -- Main must record
verdicts, never author them. Worse, the gap was declared "fixed" once and
regressed, and a later claim that the file was "GENERATED and cannot silently
lag again" was itself unbacked: no generator existed. This script is that
mechanism, so the claim is true by construction rather than by intention.

INPUTS  handoff/current/evaluator_critique_<step>_cycle<N>.json
        (raw structured returns; a file with no "verdict" key -- e.g. an
        ERRORED run -- is recorded as a non-verdict and never counted)
OUTPUT  handoff/current/evaluator_critique_<step>.md

Usage:
    python scripts/harness/build_evaluator_critique.py 82.0
    python scripts/harness/build_evaluator_critique.py 82.0 --check   # CI/no-write
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

HANDOFF = os.path.join("handoff", "current")


def cycle_files(step: str) -> list[tuple[int, str]]:
    pat = os.path.join(HANDOFF, f"evaluator_critique_{step}_cycle*.json")
    out = []
    for f in glob.glob(pat):
        m = re.search(r"_cycle(\d+)", os.path.basename(f))
        if m:
            out.append((int(m.group(1)), f))
    return sorted(out)


def render(step: str) -> str:
    files = cycle_files(step)
    if not files:
        raise SystemExit(f"no cycle JSON found for step {step} under {HANDOFF}/")

    verdicts, sections = [], []
    for n, f in files:
        d = json.load(open(f, encoding="utf-8"))
        v = d.get("verdict")
        if not v:
            verdicts.append(f"cycle {n} = _{d.get('outcome', 'NO VERDICT')}_")
            sections.append(
                f"\n---\n\n## Cycle {n} -- NO VERDICT\n\n"
                f"```json\n{json.dumps(d, indent=2, ensure_ascii=False)}\n```\n\n"
                "An errored or empty return is **not a verdict**. It does not advance the\n"
                "consecutive-CONDITIONAL counter and never counts as a PASS.\n"
            )
            continue
        verdicts.append(f"cycle {n} = **{v}**")
        checks = d.get("checks_run", [])
        sections.append(
            f"\n---\n\n## Cycle {n} -- Q/A verdict **{v}**\n\n"
            f"`ok: {d.get('ok')}` | `certified_fallback: {d.get('certified_fallback')}` "
            f"| `harness_compliance_ok: {d.get('harness_compliance_ok')}`\n\n"
            f"**violated_criteria:** "
            f"{json.dumps(d.get('violated_criteria', []), ensure_ascii=False, indent=1)}\n\n"
            f"### reason (verbatim)\n\n> {(d.get('reason') or '').strip()}\n\n"
            f"### checks_run ({len(checks)})\n\n"
            + "\n".join("- `" + c + "`" for c in checks) + "\n"
        )

    header = (
        f"# Evaluator critique -- step {step}\n\n"
        "Transcribed VERBATIM from the Q/A return values. Main records verdicts;\n"
        "Main never authors them.\n\n"
        "**GENERATED by `scripts/harness/build_evaluator_critique.py` from the\n"
        f"`evaluator_critique_{step}_cycle<N>.json` returns.** Do not hand-edit --\n"
        "re-run the script instead. `--check` fails if this file is stale, so the\n"
        "record cannot silently fall behind the raw returns.\n\n"
        "Verdict history: " + " -> ".join(verdicts) + "\n"
    )
    return header + "".join(sections)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("step")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the rendered output differs from the file on disk")
    a = ap.parse_args()

    out_path = os.path.join(HANDOFF, f"evaluator_critique_{a.step}.md")
    rendered = render(a.step)

    if a.check:
        cur = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else ""
        if cur != rendered:
            print(f"STALE: {out_path} does not match the cycle JSON returns")
            return 1
        print(f"OK: {out_path} is in sync")
        return 0

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {out_path} ({len(rendered)} chars) from {len(cycle_files(a.step))} cycle files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
