#!/usr/bin/env python3
"""Regenerate the scheduler figure-probe positive control (phase-86.94 cycle 6).

WHY THIS EXISTS. `verify_no_sliding_windows_86_94.py` asserts a criterion-4
judgement about `backend/slack_bot/scheduler.py`'s `--since-as-filter=midnight`
window, and binds that judgement to figure probes. A probe needs a positive
control, or a silently dead probe is indistinguishable from a measured absence.

Cycle 5 wrote those controls by hand and claimed their provenance in a comment.
The cycle-5 Q/A falsified the claim by execution: a probe and a fixture
co-written from one misreading passed the guard cleanly, because nothing checked
that a fixture came from anywhere real. So the control is now a COMMITTED FILE
produced by EXECUTING the renderer, and the guard asserts the fixture text is
actually present in the tracked file it names.

The output lives under `scripts/qa/fixtures/` and NOT under `handoff/**.md` on
purpose: it is deliberately outside the `[3b]` quote corpus. A fixture proves the
probe recognises the figure SHAPE; the corpus search answers the different
question of whether that figure was ever quoted AS EVIDENCE. If fixtures lived
inside the corpus, every claim would be forced to True by construction.

Run:  python scripts/qa/gen_shipped_today_fixture_86_94.py
Then: git add scripts/qa/fixtures/shipped_today_render_86_94.txt
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from backend.slack_bot.formatters import format_away_digest_sections  # noqa: E402

OUT = REPO / "scripts/qa/fixtures/shipped_today_render_86_94.txt"

# Fixed sample input. The commit subjects are real but any content works -- what
# the control captures is the RENDERED SHAPE, which is what the probe must match.
# The shape is not obvious from the call site: formatters.py:102-109 appends the
# body, but add() at :71-76 wraps it as `*{title}*\n{body}`, and reading only the
# former is exactly how the cycle-4 probe came to be blind to its own subject.
SAMPLE = {
    "commits_today": [
        "8853e74c chore: auto-changelog hook entry for c4b84e4e",
        "c4b84e4e docs(session): overnight day report + regenerated goal_next",
    ],
    "steps_flipped_today": ["86.92"],
}

HEADER = (
    "# GENERATED by executing backend.slack_bot.formatters.format_away_digest_sections\n"
    "# phase-86.94 cycle 6. Regenerate with scripts/qa/gen_shipped_today_fixture_86_94.py.\n"
    "# Purpose: provenance for the scheduler figure-probe positive control.\n"
    "# NOTE this file is deliberately OUTSIDE the [3b] quote corpus (not handoff/**.md).\n\n"
)


def render() -> str:
    sections = format_away_digest_sections(SAMPLE)
    return "\n".join(
        s.get("text", {}).get("text", "")
        for s in sections
        if isinstance(s, dict) and isinstance(s.get("text"), dict)
    )


def main() -> int:
    rendered = render()
    # Fail loudly rather than writing a control that proves nothing.
    if "*Shipped today*" not in rendered:
        print("REFUSING TO WRITE: the render does not contain the 'Shipped today' "
              "section. The renderer changed shape -- re-derive the probe before "
              "regenerating this fixture.", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + rendered + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(rendered)} chars of render)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
