#!/usr/bin/env python3
"""phase-86.20 criterion 2 -- re-derive the recommendation population.

Criterion 2 requires the population to be RE-DERIVED at fix time rather than
copied from the step text, and to record every distinct value, its count, how
many are genuine (`final_score > 0`), and which values match the gate. This
script is that measurement, so the number in the artifact is generated by a
command instead of hand-copied -- three prior Q/A cycles on a sibling step died
on hand-copied figures that the next edit invalidated.

It is READ-ONLY: one bounded, cache-disabled `GROUP BY` against the SAME table
and column `decide_trades` consumes, resolved through the settings rather than
hardcoded, so a dataset rename cannot silently point this at the wrong place.

    source .venv/bin/activate
    python scripts/qa/measure_86_20_recommendation_population.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# `python scripts/qa/<name>.py` puts scripts/qa on sys.path[0], not the repo
# root, so the backend package is not importable without this.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from google.cloud import bigquery  # noqa: E402

from backend.config.settings import get_settings  # noqa: E402
from backend.services.portfolio_manager import (  # noqa: E402
    _BUY_RECS, _DOWNGRADE_RECS, _SELL_RECS,
)
from backend.services.recommendation_vocab import canonical_recommendation  # noqa: E402


def _legacy(value) -> str:
    """Exactly what the pre-86.20 expression produced: `(v or "HOLD").upper()`."""
    return (value or "HOLD").upper()


def main() -> int:
    s = get_settings()
    table = f"{s.gcp_project_id}.{s.bq_dataset_reports}.{s.bq_table_reports}"
    print(f"phase-86.20 criterion 2 -- recommendation population")
    print(f"table (resolved from settings, not hardcoded): {table}")
    print(f"_BUY_RECS={sorted(_BUY_RECS)} _SELL_RECS={sorted(_SELL_RECS)} "
          f"_DOWNGRADE_RECS={sorted(_DOWNGRADE_RECS)}\n")

    client = bigquery.Client(project=s.gcp_project_id)
    rows = list(
        client.query(
            f"""
            SELECT recommendation,
                   COUNT(*)                    AS n,
                   COUNTIF(final_score > 0)    AS genuine,
                   MAX(final_score)            AS max_score,
                   MAX(IF(final_score > 0, final_score, NULL)) AS max_genuine
            FROM `{table}`
            GROUP BY recommendation
            ORDER BY n DESC
            LIMIT 100
            """,
            job_config=bigquery.QueryJobConfig(use_query_cache=False),
        ).result(timeout=30)
    )

    hdr = (f"{'value':<14}{'n':>5}{'genuine':>8}{'maxgen':>8}   "
           f"{'legacy':<14}{'BUY':>6}{'SELL':>6}{'DOWN':>6}    "
           f"{'canonical':<13}{'BUY':>6}{'SELL':>6}{'DOWN':>6}   VERDICT")
    print(hdr)
    print("-" * len(hdr))

    fixed_buy = fixed_sell = fixed_down = unrecognised = 0
    for r in rows:
        v = r.recommendation
        lg = _legacy(v)
        cn = canonical_recommendation(v if v is not None else "HOLD")
        lb, ls, ld = lg in _BUY_RECS, lg in _SELL_RECS, lg in _DOWNGRADE_RECS
        cb = cn in _BUY_RECS if cn else False
        cs = cn in _SELL_RECS if cn else False
        cd = cn in _DOWNGRADE_RECS if cn else False

        if cn is None:
            verdict = "UNRECOGNISED (no gate, either way)"
            unrecognised += r.n
        elif (lb, ls, ld) == (cb, cs, cd):
            verdict = "unchanged"
        else:
            gained = []
            if cb and not lb:
                gained.append("BUY"); fixed_buy += r.n
            if cs and not ls:
                gained.append("SELL"); fixed_sell += r.n
            if cd and not ld:
                gained.append("DOWNGRADE"); fixed_down += r.n
            verdict = "FIXED: now reaches " + "+".join(gained) if gained else "changed"

        mg = "-" if r.max_genuine is None else f"{r.max_genuine:.2f}"
        print(f"{str(v):<14}{r.n:>5}{r.genuine:>8}{mg:>8}   "
              f"{lg!r:<14}{str(lb):>6}{str(ls):>6}{str(ld):>6}    "
              f"{str(cn):<13}{str(cb):>6}{str(cs):>6}{str(cd):>6}   {verdict}")

    print(f"\nrows whose BUY gate is FIXED       : {fixed_buy}")
    print(f"rows whose SELL gate is FIXED      : {fixed_sell}")
    print(f"rows whose DOWNGRADE gate is FIXED : {fixed_down}")
    print(f"rows UNRECOGNISED by the closed scale: {unrecognised}")
    print("\nNOTE: reaching a gate is NOT trading. Risk Judge sizing, sector caps")
    print("and available cash all sit downstream. No lost-trade or lost-P&L claim")
    print("is licensed by this table.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
