#!/usr/bin/env python3
"""phase-36.17 criterion 7 -- re-runnable mutation matrix.

WHY THIS FILE EXISTS
--------------------
Criterion 7 requires every new guard to be mutation-tested, in BOTH directions
for the ordering change. The cycle-1..5 matrices were produced by a scratch
script that was never committed, so the transcript in the step artifacts could
not be regenerated by anyone -- including me. This harness makes criterion 7
re-runnable.

SAFETY -- THIS HARNESS NEVER WRITES TO THE REPOSITORY
-----------------------------------------------------
An earlier scratch harness mutated the LIVE
`backend/services/autonomous_loop.py` while an ARMED backend was running. No
harm occurred (CPython serves an imported module from `sys.modules` and never
re-reads the file), but a restart inside any of those windows would have
imported a mutant into an armed trading process, and a tool timeout did once
leave a mutant on disk.

So each mutant here is applied **in memory**, inside a throwaway subprocess
that registers the mutated module object in `sys.modules` BEFORE pytest
imports anything. The on-disk file is opened read-only and never rewritten.
`--verify-clean` (default on) digests the target before and after the whole
run and fails if they differ.

DISCIPLINE ENCODED HERE
-----------------------
* Every mutation anchor must occur **exactly once** in the source. A
  no-match `str.replace` is indistinguishable from success, so an anchor that
  matches 0 or 2+ times is a hard error, not a skipped cell.
* The mutated source must differ from the original -- asserted, not assumed.
* The un-mutated **baseline must be GREEN first**. A "killed" mutant proves
  nothing if the tree was already red.
* A **restored** run is executed last, so the transcript shows the tree green
  on both sides of the matrix.
* Each cell runs the WHOLE module (no `-k` filter), so the transcript names
  which tests catch the mutant and carries no `deselected` count -- that count
  moves every time the step adds a test and has gone stale three times.

USAGE
-----
    source .venv/bin/activate
    python scripts/qa/mutation_matrix_36_17.py

Do NOT run this concurrently with any other pytest invocation: the module's
autouse `_live_audit_file_is_write_protected` fixture byte-compares the live
`handoff/kill_switch_audit.jsonl`, so a second run turns this one RED.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET = REPO_ROOT / "backend" / "services" / "autonomous_loop.py"
MODNAME = "backend.services.autonomous_loop"
TEST_MODULE = "backend/tests/test_phase_36_17_halt_stop_loss_enforcement.py"

# ── the matrix ───────────────────────────────────────────────────────────────
# Each cell: (id, description, what it proves, old, new).
# `old` carries enough surrounding context to be UNIQUE in the file; the
# harness asserts that before mutating.

_ANCHOR_SCOPE_GUARD = (
    '                if not ks_check.get("triggered"):\n'
    '                    summary["halt_stop_loss_triggered"] = []'
)

MUTANTS: list[dict] = [
    {
        "id": "M1",
        "desc": "delete the halt's `return summary` (cycle falls through to decide/execute)",
        "proves": "criterion 4 no-BUY -- the halt must return before Step 6",
        "old": "                _last_result = summary\n                return summary\n",
        "new": "                _last_result = summary\n                pass  # MUTANT M1: halt no longer returns\n",
    },
    {
        "id": "M2",
        "desc": "ORDERING REVERTED: disable the exit-only pass entirely (pre-fix behaviour)",
        "proves": "criteria 1+2+7 -- moving the enforcement back must break the reproduce pair",
        "old": _ANCHOR_SCOPE_GUARD,
        "new": _ANCHOR_SCOPE_GUARD.replace(
            'if not ks_check.get("triggered"):', "if False:  # MUTANT M2"
        ),
    },
    {
        "id": "M3",
        "desc": "remove the breach-path exclusion (the pass runs on EVERY halt reason)",
        "proves": "criterion 5 -- the `triggered` path must stay observably unchanged",
        "old": _ANCHOR_SCOPE_GUARD,
        "new": _ANCHOR_SCOPE_GUARD.replace(
            'if not ks_check.get("triggered"):', "if True:  # MUTANT M3"
        ),
    },
    {
        "id": "M4",
        "desc": "reintroduce backfill_missing_stops into the halt pass",
        "proves": "research Q3 -- synthesizing a stop during a halt is a NEW risk decision",
        "old": "                        halt_stops = await asyncio.to_thread(trader.check_stop_losses)",
        "new": (
            "                        await asyncio.to_thread(trader.backfill_missing_stops)  # MUTANT M4\n"
            "                        halt_stops = await asyncio.to_thread(trader.check_stop_losses)"
        ),
    },
    {
        "id": "M5",
        "desc": 'append to summary["steps"] inside the halt branch',
        "proves": "measured collision -- two phase-36.12 tests pin summary['steps'][-1]",
        "old": '                    summary["halt_stop_loss_triggered"] = []',
        "new": (
            '                    summary["halt_stop_loss_triggered"] = []\n'
            '                    summary["steps"].append("stop_loss_enforcement")  # MUTANT M5'
        ),
    },
    {
        "id": "M6",
        "desc": "drop the recorded ticker (silent enforcement, no audit surface)",
        "proves": "the exit must be REPORTED in the summary, not just performed",
        "old": '                                summary["halt_stop_loss_triggered"].append(sl_ticker)',
        "new": "                                pass  # MUTANT M6: ticker not recorded",
    },
    {
        "id": "M-D",
        "desc": "`if sl_trade:` -> `if True:` (record an exit that never happened)",
        "proves": "Q/A cycle-3 survivor -- the summary must not claim a stop it did not take",
        "old": "                            if sl_trade:\n",
        "new": "                            if True:  # MUTANT M-D\n",
    },
    {
        "id": "M-E",
        "desc": "drop summary['halt_stop_loss_error'] (silent swallow)",
        "proves": "Q/A cycle-3 survivor -- a stop-loss failure must not be swallowed",
        "old": '                        summary["halt_stop_loss_error"] = repr(halt_sl_exc)\n',
        "new": "                        pass  # MUTANT M-E: error record dropped\n",
    },
    {
        "id": "M-F",
        "desc": "logger.exception -> logger.debug (downgrade the loudness)",
        "proves": "paired with M-E; the log level is the half the summary key cannot carry",
        "old": (
            "                        logger.exception(\n"
            '                            "phase-36.17: exit-only stop-loss pass FAILED on a "'
        ),
        "new": (
            "                        logger.debug(  # MUTANT M-F\n"
            '                            "phase-36.17: exit-only stop-loss pass FAILED on a "'
        ),
    },
    {
        "id": "MUT-B",
        "desc": "`quantity=None` -> `quantity=1` (a ONE-SHARE exit reported as enforced)",
        "proves": "Q/A cycle-5 survivor -- a partial fill must not count as a full exit",
        "old": (
            "                                ticker=sl_ticker,\n"
            "                                quantity=None,\n"
        ),
        "new": (
            "                                ticker=sl_ticker,\n"
            "                                quantity=1,  # MUTANT MUT-B\n"
        ),
    },
    {
        "id": "MUT-C",
        "desc": "delete the halt-path mark_to_market (stops compared against STALE marks)",
        "proves": "Q/A cycle-5 survivor -- §1 claims mark freshness as load-bearing",
        "old": (
            "                final_state = await asyncio.to_thread(trader.mark_to_market)\n"
            "\n"
            "                # ── phase-36.17: EXIT-ONLY pass on a halted cycle ────────"
        ),
        "new": (
            "                # MUTANT MUT-C: halt-path mark_to_market deleted\n"
            "\n"
            "                # ── phase-36.17: EXIT-ONLY pass on a halted cycle ────────"
        ),
    },
]

# The bootstrap that runs inside each subprocess. It injects the (possibly
# mutated) module into sys.modules BEFORE pytest imports anything, so nothing
# is ever written to disk.
BOOTSTRAP = r"""
import importlib.util, json, os, sys

spec = json.load(open(os.environ["MUT3617_SPEC"], encoding="utf-8"))
target, modname = spec["target"], spec["modname"]
src = open(target, encoding="utf-8").read()
original = src

old, new = spec.get("old"), spec.get("new")
if old is not None:
    n = src.count(old)
    if n != 1:
        sys.stderr.write("ANCHOR NOT UNIQUE: %d occurrence(s)\n" % n)
        raise SystemExit(97)
    src = src.replace(old, new, 1)
    if src == original:
        sys.stderr.write("MUTATION WAS A NO-OP\n")
        raise SystemExit(96)

import backend.services  # parent package; empty __init__

mod = importlib.util.module_from_spec(
    importlib.util.spec_from_file_location(modname, target)
)
sys.modules[modname] = mod
exec(compile(src, target, "exec"), mod.__dict__)
setattr(sys.modules["backend.services"], "autonomous_loop", mod)

import pytest
raise SystemExit(pytest.main(spec["pytest_args"]))
"""


def _md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def _run(old: str | None, new: str | None) -> tuple[int, str]:
    """Run the test module against an in-memory (possibly mutated) source."""
    payload = {
        "target": str(TARGET),
        "modname": MODNAME,
        "old": old,
        "new": new,
        "pytest_args": [TEST_MODULE, "-q", "-p", "no:randomly", "--no-header"],
    }
    fd, spec_path = tempfile.mkstemp(prefix="mut3617_", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh)
        env = dict(os.environ, MUT3617_SPEC=spec_path, PYTHONDONTWRITEBYTECODE="1")
        proc = subprocess.run(
            [sys.executable, "-c", BOOTSTRAP],
            cwd=str(REPO_ROOT),
            env=env,
            capture_output=True,
            text=True,
        )
    finally:
        os.unlink(spec_path)
    return proc.returncode, (proc.stdout + proc.stderr)


def _summary_line(out: str) -> str:
    """The pytest one-line summary (last non-empty line that names a count)."""
    for line in reversed(out.strip().splitlines()):
        s = line.strip()
        if ("passed" in s or "failed" in s or "error" in s) and " in " in s:
            return s.strip("= ").strip()
    return "NO SUMMARY (see stderr)"


def _failed_tests(out: str) -> list[str]:
    names = []
    for line in out.splitlines():
        if line.startswith("FAILED "):
            frag = line.split(" ", 1)[1].split(" ")[0]
            names.append(frag.rsplit("::", 1)[-1])
    return names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="run a single mutant by id")
    args = ap.parse_args()

    digest_before = _md5(TARGET)
    print("phase-36.17 criterion 7 -- mutation matrix")
    print(f"target   : {TARGET.relative_to(REPO_ROOT)}")
    print(f"md5      : {digest_before}  (read-only; mutants are in-memory)")

    rc, out = _run(None, None)
    baseline = _summary_line(out)
    print(f"[baseline] un-mutated tree: {baseline}")
    if rc != 0:
        print("BASELINE IS RED -- aborting. A 'killed' mutant proves nothing here.")
        print(out[-4000:])
        return 2

    cells = [m for m in MUTANTS if not args.only or m["id"] == args.only]
    killed, survived, broken = 0, [], []

    for m in cells:
        rc, out = _run(m["old"], m["new"])
        summary = _summary_line(out)
        if rc in (96, 97):
            broken.append(m["id"])
            verdict = "BROKEN"
        elif rc == 0:
            survived.append(m["id"])
            verdict = "SURVIVED"
        else:
            killed += 1
            verdict = "KILLED  "
        print(f"  {verdict}| {m['id']}: {m['desc']}")
        print(f"           proves: {m['proves']}")
        tests = _failed_tests(out)
        if tests:
            print(f"           tests : {', '.join(tests)}")
        print(f"           result: {summary}")

    rc, out = _run(None, None)
    print(f"[restored] un-mutated tree: {_summary_line(out)}")

    digest_after = _md5(TARGET)
    same = digest_before == digest_after
    print(f"[integrity] target md5 unchanged: {same} ({digest_after})")

    total = len(cells)
    if broken:
        print(f"MATRIX BROKEN -- anchors failed for: {', '.join(broken)}")
        return 3
    if survived:
        print(f"{killed} of {total} killed. SURVIVORS: {', '.join(survived)}")
        return 1
    if not same:
        print("TARGET FILE CHANGED DURING THE RUN -- investigate before trusting this.")
        return 4
    # SCOPED deliberately. "Every new guard can fail" is a GLOBAL claim this
    # matrix does not license -- the cycle-5 Q/A said so and was right. This
    # matrix mutates autonomous_loop.py only, so it can speak for the guards
    # over the halt-branch pass and nothing else. The test-isolation guards in
    # the same module are proven falsifiable separately, by demonstration.
    print(f"ALL {total} MUTANTS KILLED -- every guard IN THIS MATRIX can fail.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
