#!/usr/bin/env python3
"""phase-86.27 criterion 7 -- mutation matrix for the live-origin guard.

RE-RUNNABLE AND HERMETIC, and both properties are deliberate.

* **Re-runnable**, because phase-36.17 burned five Q/A cycles on a scratch
  mutation harness that was never committed: the transcript could not be
  regenerated by anyone, so the evidence was unauditable.
* **Hermetic**, because the obvious harness -- mutate the real
  `scripts/qa/live_backend_origin.py`, run, restore -- leaves the repository
  broken if it crashes mid-run, AND a concurrent Claude session is working in
  this same tree today. Every mutation here is applied to a COPY in a temp
  directory, loaded by a CHILD process from that directory. The tracked file is
  never written.

Each cell states the property it expects to break. A mutant that produces the
SAME answer as the control has SURVIVED, and a surviving mutant means the guard
it targets is not actually load-bearing -- which does not count as covered.

Anchor uniqueness is asserted for every mutation: a `str.replace` that matches
nothing looks exactly like a successful edit and would silently score a
non-mutation as a kill.

    $ python scripts/qa/mutation_matrix_86_27.py
"""
from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]
SRC = REPO / "scripts" / "qa" / "live_backend_origin.py"

#: (id, anchor, replacement, probe expression, description)
#: The probe is evaluated in a child against the mutated module; the cell is
#: KILLED when the mutant's answer differs from the control's.
MUTATIONS = [
    ("M1",
     "    return targets_this_machine(host) if isinstance(host, str) else False",
     "    return host in LOOPBACK_HOSTS",
     "address_is_live_backend(('127.1', 8000))",
     "revert the address predicate to the four-string allowlist"),

    ("M2",
     "    if ip.is_loopback or ip.is_unspecified:\n        return True",
     "    if ip.is_loopback:\n        return True",
     "_is_this_machine('0.0.0.0')",
     "drop the wildcard (is_unspecified) leg -- 0.0.0.0 reaches the book"),

    # The probe here is a MAPPED NON-LOOPBACK address, derived at runtime, and
    # that is not a detail. The first draft probed `::ffff:127.0.0.1` and the
    # mutant SURVIVED, because CPython already reports
    # `IPv6Address('::ffff:127.0.0.1').is_loopback == True` -- it classifies
    # through the mapped address itself. So for loopback the branch really is
    # redundant, and only a mapped address of a NON-loopback interface shows
    # that it carries weight. Same shape as phase-86.6's M4/M5 pair: a leg is
    # proven load-bearing only by a case the other legs cannot reach.
    ("M3",
     "    mapped = getattr(ip, \"ipv4_mapped\", None)\n"
     "    if mapped is not None and _is_this_machine(str(mapped)):\n"
     "        return True",
     "    pass",
     "_is_this_machine('::ffff:' + next(a for a in sorted(m.own_addresses()) "
     "if ':' not in a and not a.startswith('127.')))",
     "drop the IPv4-mapped IPv6 unwrapping (probed on a mapped LAN address, "
     "since CPython already handles mapped LOOPBACK on its own)"),

    ("M4",
     "    verdict = True if addrs is None else any(_is_this_machine(a) for a in addrs)",
     "    verdict = False if addrs is None else any(_is_this_machine(a) for a in addrs)",
     "targets_this_machine('no-such-host-86-27-probe.invalid')",
     "fail OPEN instead of fail SAFE on an unresolvable host "
     "(this is the percent-encoded bypass)"),

    ("M5",
     "        if int(port) != int(live_port):\n            return False",
     "        pass",
     "address_is_live_backend(('127.0.0.1', 59999))",
     "drop the port check -- every 4000.2 ephemeral stub becomes 'live'"),

    # Probed on a REMOTE numeric address, and again the first draft got this
    # wrong: it probed `2130706433` (loopback), where the control answer True
    # and the mutant's fail-safe True coincide, so the cell could not
    # discriminate. A mutant is only killed by a case where the guard's answer
    # and its failure mode DIFFER.
    ("M6",
     "    for flags in (socket.AI_NUMERICHOST, 0):",
     "    for flags in ():",
     "targets_this_machine('8.8.8.8')",
     "remove canonicalisation entirely -- nothing resolves, so everything "
     "fails safe and the predicate stops discriminating at all"),

    ("M7",
     "    if ip.is_loopback or ip.is_unspecified:\n        return True",
     "    if ip.is_loopback or ip.is_unspecified:\n        return True\n"
     "    return True",
     "targets_this_machine('8.8.8.8')",
     "blanket TRUE -- the guard refuses everything, incl. genuinely remote hosts"),
]

CHILD = r'''
import json, sys
sys.path.insert(0, sys.argv[1])
import live_backend_origin as m
from live_backend_origin import (address_is_live_backend, targets_this_machine,
                                 _is_this_machine, LOOPBACK_HOSTS)
try:
    print(json.dumps({"ok": True, "value": repr(eval(sys.argv[2]))}))
except Exception as e:
    print(json.dumps({"ok": False, "value": f"{type(e).__name__}: {e}"}))
'''


def run_probe(module_dir: pathlib.Path, probe: str) -> dict:
    p = subprocess.run([sys.executable, "-c", CHILD, str(module_dir), probe],
                       capture_output=True, text=True, timeout=120)
    if p.returncode != 0:
        return {"ok": False, "value": f"child rc={p.returncode} {p.stderr[-300:]}"}
    return json.loads(p.stdout.strip().splitlines()[-1])


def main() -> int:
    original = SRC.read_text()
    rows, survived = [], []

    with tempfile.TemporaryDirectory(prefix="mm8627_") as td:
        base = pathlib.Path(td)
        control_dir = base / "control"
        control_dir.mkdir()
        shutil.copy2(SRC, control_dir / SRC.name)

        for mid, anchor, repl, probe, desc in MUTATIONS:
            # ANCHOR UNIQUENESS. A no-match replace is indistinguishable from a
            # successful one by its return value, so it is asserted, not hoped.
            n = original.count(anchor)
            if n != 1:
                rows.append((mid, "ANCHOR", f"matched {n} time(s)", desc))
                survived.append(mid)
                continue

            mut_dir = base / mid
            mut_dir.mkdir()
            (mut_dir / SRC.name).write_text(original.replace(anchor, repl, 1))

            control = run_probe(control_dir, probe)
            mutant = run_probe(mut_dir, probe)
            killed = control != mutant
            rows.append((mid, "KILLED" if killed else "SURVIVED",
                         f"control={control['value']}  mutant={mutant['value']}",
                         desc))
            if not killed:
                survived.append(mid)

    # The tracked file was never opened for writing; assert it anyway, because
    # "I did not write it" is exactly the kind of claim worth proving.
    assert SRC.read_text() == original, "the tracked source CHANGED -- aborting"

    w = max(len(r[3]) for r in rows)
    print(f"{'id':4} {'verdict':9} {'probe':52} mutation")
    print("-" * (68 + w))
    for mid, verdict, detail, desc in rows:
        print(f"{mid:4} {verdict:9} {detail[:52]:52} {desc}")
    print("-" * (68 + w))
    print(f"tracked source UNCHANGED (sha-equal to start): "
          f"{SRC.read_text() == original}")
    if survived:
        print(f"\nSURVIVING MUTANTS: {survived} -- these guards are NOT proven "
              f"load-bearing and do not count as covered.")
        return 1
    print(f"\nAll {len(rows)} mutants killed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
