steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/pyfinagent/pyfinagent-app:latest'
  - '.'

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/pyfinagent/pyfinagent-app:latest'

# 3. Deploy container image to Cloud Run and mount secrets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pyfinagent-app' # The name of your Cloud Run service
  - '--region=${_LOCATION}'
  - '--image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/pyfinagent/pyfinagent-app:latest'
  - '--platform=managed'
  - '--allow-unauthenticated' # Use --no-allow-unauthenticated for a private service

options:
  substitution_option: 'ALLOW_LOOSE'