/**
 * Centralized Phosphor icon exports.
 * Import from here instead of @phosphor-icons/react directly for consistency.
 *
 * phase-16.39 (#50): all 22 prior violators rewritten to import from here;
 * ESLint rule promoted from "warn" to "error" alongside this sweep.
 */
export type { Icon } from "@phosphor-icons/react";

export {
  // ── Navigation ──
  House as NavHome,
  Brain as NavAnalyze,
  Broadcast as NavSignals,
  Files as NavReports,
  ChartLineUp as NavPerformance,
  Wallet as NavPortfolio,
  Robot as NavPaperTrading,
  ClockCounterClockwise as NavBacktest,
  Gear as NavSettings,
  // phase-16.33: sovereign view nav icon (alpha leaderboard / red-line monitor / champion strategy)
  Crown as NavSovereign,
  ChartLineUp as LogoIcon,

  // ── Analysis Pipeline Steps ──
  Newspaper as StepMarketIntel,
  CloudArrowDown as StepIngestion,
  HashStraight as StepQuant,
  FileText as StepRag,
  Crosshair as StepSentiment,
  Trophy as StepCompetitor,
  Broadcast as StepEnrichment,
  MagnifyingGlass as StepInfoGap,
  Brain as StepSignalAnalysis,
  Scales as StepDebate,
  GlobeHemisphereWest as StepMacro,
  Binoculars as StepDeepDive,
  Flask as StepSynthesis,
  ShieldCheck as StepBiasAudit,
  Bank as StepRiskAssessment,
  Timer as IconTimer,

  // ── Signal Icons ──
  UserCircle as SignalInsider,
  ChartBar as SignalOptions,
  ChatCircle as SignalSocial,
  Lightbulb as SignalPatent,
  Microphone as SignalEarnings,
  Bank as SignalMacro,
  TrendUp as SignalAltData,
  Factory as SignalSector,
  Brain as SignalNlp,
  Warning as SignalAnomaly,
  DiceFive as SignalMonteCarlo,
  ChartPieSlice as SignalQuantModel,

  // ── Debate Icons ──
  TrendUp as DebateBull,
  TrendDown as DebateBear,
  Scales as DebateConsensus,
  Lightning as DebateContradiction,
  Detective as DebateDevilsAdvocate,
  Repeat as DebateRounds,
  ListBullets as DebateDissent,

  // ── Risk Team Icons ──
  Sword as RiskAggressive,
  Shield as RiskConservative,
  Scales as RiskNeutral,
  Gavel as RiskJudge,

  // ── Bias & Audit Icons ──
  Monitor as BiasTech,
  ArrowsClockwise as BiasConfirmation,
  Clock as BiasRecency,
  Anchor as BiasAnchoring,
  ChartBar as BiasDiversity,
  ShieldWarning as BiasDefault,
  ShieldCheck as BiasShield,
  Lightning as ConflictIcon,
  TreeStructure as TraceIcon,
  Lightbulb as SuggestionIcon,
  MagnifyingGlass as AuditIcon,

  // ── Evaluation Pillar Icons ──
  Buildings as PillarCorporate,
  GlobeHemisphereWest as PillarIndustry,
  CurrencyDollar as PillarValuation,
  ChartBar as PillarSentiment,
  Bank as PillarGovernance,

  // ── Macro Indicator Icons ──
  Bank as MacroFedFunds,
  CurrencyDollar as MacroCpi,
  HardHat as MacroUnemployment,
  ChartBar as MacroGdp,
  TrendDown as MacroYieldSpread,
  ShoppingCart as MacroConsumer,
  Bank as MacroTreasury,
  Ruler as MacroDefault,

  // phase-16.30 identity re-export so RedLineMonitor (and any other
  // alpha/risk component) can use the canonical Phosphor name without
  // importing directly from @phosphor-icons/react. Keeps the
  // .claude/rules/frontend.md "icons via @/lib/icons" rule satisfied.
  TrendDown as TrendDown,

  // phase-23.1.6 — Signal Stack canonical exports for Settings page
  Newspaper as Newspaper,
  GlobeHemisphereWest as GlobeHemisphereWest,
  CalendarBlank as CalendarBlank,

  // ── GlassBox Icons ──
  Gauge as IconAlphaScore,
  MagnifyingGlass as IconSummary,
  ChartBar as IconScoringMatrix,
  Warning as IconKeyRisks,

  // ── Tab Icons (page.tsx) ──
  ClipboardText as TabOverview,
  Broadcast as TabSignals,
  Scales as TabDebate,
  Crosshair as TabRisk,
  MagnifyingGlass as TabAudit,
  CurrencyDollar as TabCost,

  // ── Settings Icons ──
  Lightning as SettingsMode,
  ChatTeardropDots as SettingsDebate,
  Brain as SettingsModel,
  ShieldCheck as SettingsCostControls,
  CurrencyDollar as SettingsEstimator,
  ChartBar as SettingsPillars,
  Database as SettingsCache,
  GearSix as SettingsOptimizer,
  Timer as SettingsLatency,
  ArrowClockwise as SettingsRefresh,

  // ── Utility ──
  DownloadSimple as IconDownload,
  Key as IconKey,
  SignOut as IconSignOut,
  Check as IconCheck,
  X as IconX,
  SpinnerGap as IconSpinner,
  Sparkle as IconDeepThink,
  ChartLineUp as IconChart,
  Funnel as IconFilter,
  CaretDown as IconCaretDown,
  CaretRight as IconCaretRight,
  Eye as IconEye,
  EyeSlash as IconEyeSlash,
  Star as IconStar,
  Football as IconValuation,
  Warning as IconWarning,
  MagnifyingGlass as IconSearch,
  Crosshair as IconTarget,
  RocketLaunch as IconRocket,
  TrendUp as IconTrendUp,
  CheckCircle as IconCheckCircle,
  XCircle as IconXCircle,
  Info as IconInfo,

  // ── phase-16.39 sweep additions (icons formerly imported directly) ──
  ArrowsLeftRight as IconArrowsLeftRight,
  CaretLeft as IconCaretLeft,
  CaretUp as IconCaretUp,
  ChartBarHorizontal as IconChartBarHorizontal,
  ChartPolar as IconChartPolar,
  LineSegments as IconLineSegments,
  NotePencil as IconNotePencil,
  Play as IconPlay,
  Stop as IconStop,
  Table as IconTable,
  Target as IconTargetAlt,
  Trash as IconTrash,
  // identity re-exports for icons that some files use under their bare
  // Phosphor name (avoid renames in those files; keep diffs surgical):
  ArrowClockwise as ArrowClockwise,
  ArrowsClockwise as ArrowsClockwise,
  ArrowsLeftRight as ArrowsLeftRight,
  Bank as Bank,
  Brain as Brain,
  Broadcast as Broadcast,
  Buildings as Buildings,
  CaretDown as CaretDown,
  CaretLeft as CaretLeft,
  CaretUp as CaretUp,
  ChatCircle as ChatCircle,
  ChartBar as ChartBar,
  ChartBarHorizontal as ChartBarHorizontal,
  ChartLineUp as ChartLineUp,
  ChartPolar as ChartPolar,
  // phase-25.B12: aliases for paper-trading tab icons (frontend-layout.md §5)
  Wallet as TabPositions,
  Receipt as TabTrades,
  ChartLineUp as TabNavChart,
  ChartBar as TabRealityGap,
  TrendUp as TabExitQuality,
  Gear as TabManage,
  Check as Check,
  CheckCircle as CheckCircle,
  ClipboardText as ClipboardText,
  Clock as Clock,
  ClockCounterClockwise as ClockCounterClockwise,
  CloudArrowDown as CloudArrowDown,
  Crosshair as Crosshair,
  Crown as Crown,
  CurrencyDollar as CurrencyDollar,
  Database as Database,
  FileText as FileText,
  Files as Files,
  Funnel as Funnel,
  Gauge as Gauge,
  Gear as Gear,
  GearSix as GearSix,
  HashStraight as HashStraight,
  House as House,
  Info as Info,
  Lightning as Lightning,
  LineSegments as LineSegments,
  ListBullets as ListBullets,
  MagnifyingGlass as MagnifyingGlass,
  NotePencil as NotePencil,
  Pause as Pause,
  Play as Play,
  Robot as Robot,
  RocketLaunch as RocketLaunch,
  Scales as Scales,
  ShieldCheck as ShieldCheck,
  ShieldWarning as ShieldWarning,
  ShoppingCart as ShoppingCart,
  Sparkle as Sparkle,
  SpinnerGap as SpinnerGap,
  Stop as Stop,
  Table as Table,
  Target as Target,
  Timer as Timer,
  Trash as Trash,
  TreeStructure as TreeStructure,
  Graph as Graph,
  TrendUp as TrendUp,
  Trophy as Trophy,
  Warning as Warning,
  X as X,
  XCircle as XCircle,
} from "@phosphor-icons/react";
